chore: move main crate to project root
also move dependencies to workspace

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -27,7 +27,11 @@ jobs:
         run: |
           cargo install cargo-rdme
           return=true
-          for dir in rustsat tools cadical kissat minisat glucose ipasir capi pyapi; do
+          if ! cargo rdme --check; then
+            echo "failed for main crate"
+            return=false
+          fi
+          for dir in tools cadical kissat minisat glucose ipasir capi pyapi; do
             cd ${dir}
             if ! cargo rdme --check; then
               echo "failed for ${dir}"
